apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
patchesStrategicMerge:
- deployment.yaml

replicas:
  - name: vote
    count: 6

images:
  - name: schoolofdevops/vote
    neTag: v6

namespace: instavote

commonLabels:
  project: instavote
  env: staging

commonAnnotations:
  supported-by: "yi"

configMapGenerator:
  - name: vote-options
    env: options.env
