apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
patchesStrategicMerge:
- deployment.yaml
replicas:
- name: vote
  count: 3
images:
- name: schoolofdevops/vote
  newName: shungli/vote
  #image: shungli/vote:main-f0988e5f-1698265460 # {"$imagepolicy": "flux-system:vote"}
  newTag: main-f50051d3-1699736460 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "yi"
configMapGenerator:
- name: vote-options
  env: options.env
