apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
patchesStrategicMerge:
- deployment.yaml
replicas:
- name: vote
  count: 7
images:
<<<<<<< HEAD
  - name: shungli/vote
    newTag: v8 # {"$imagepolicy": "flux-system:vote:tag"}

=======
- name: schoolofdevops/vote
  newTag: main-4a1ce53c-1698260747 # {"$imagepolicy": "flux-system:vote:tag"}
>>>>>>> 3f3040651aece524fe24d0f9dc18e1776945652c
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "yi"
configMapGenerator:
- name: vote-options
  env: options.env
