apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../base/
patchesStrategicMerge:
- deployment.yaml
replicas:
- name: vote
  count: 3
images:
- name: vote
  image: shungli/vote:main-393d657f-1698263841 # {"$imagepolicy": "flux-system:vote"}
  #newTag: main-393d657f-1698263841 # {"$imagepolicy": "flux-system:vote:tag"}
namespace: instavote
commonLabels:
  project: instavote
  env: staging
commonAnnotations:
  supported-by: "yi"
configMapGenerator:
- name: vote-options
  env: options.env
